### ISSUE TITLE
[1.14.4] Crash on load due to forge breaking update .45

### ISSUE THREAD

**Issue by ProsperCraft** [kreezxil/BadWitherNoCookie#5]
![51ba7f208c08e2fccfe1ee89a708f313](https://user-images.githubusercontent.com/4427684/62752297-21ca3600-ba24-11e9-940a-e83d855f94b5.png)

Version-
bwncr-1.14.4-3.5.10.jar

Stacktrace-
https://gist.github.com/ProsperCraft/57a02a434d9e6c4eb02cba98d7141e9e

Logs-
[latest.log](https://github.com/kreezxil/BadWitherNoCookie/files/3484637/latest.log)
[debug.log](https://github.com/kreezxil/BadWitherNoCookie/files/3484638/debug.log)

**Comment by eleksploded** [comment]
Should be fixed in 3.5.11, At least on my end. Could you try it please?
