### ISSUE TITLE
Badwithernocookies client side error report - crash

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/BadWitherNoCookie#6]
https://paste.ubuntu.com/p/RBTp2KtnnQ/

GrveCrvr spawned 2 withers, after spawning the second with it threw all sorts of exceptions and crashed both of our games as we were loaded into the same chunk. No other players online were affected. Issue did not occur until 2 withers were spawned at same time in same chunk.

This is on a Minecraft 1.14.4 server
Twitch Launcher
Forge version 28.1.85
Bad Wither No Cookies - reloaded version 	bwncr-1.14.4-3.5.11.jar

Crosslinked from here - https://github.com/kreezxil/World-of-Dragons-A-New-Age/issues/35

**Comment by kreezxil** [comment]
@eleksploded are you not working on this?

**Comment by kreezxil** [comment]
@Tarlin83 I believe I fixed this, please try your test again.
